# Generated by Django 3.2.7 on 2021-11-10 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido_paterno', models.CharField(max_length=10)),
                ('apellido_materno', models.CharField(max_length=10)),
                ('sede', models.CharField(max_length=10)),
                ('hora_llegada', models.TimeField(null=True)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_reunion', models.IntegerField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_por_sede', models.IntegerField(max_length=100)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.socio')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
