# Generated by Django 3.2.7 on 2021-11-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20211109_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='cantidad_por_sede',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='n_reunion',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='hora_llegada',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='hora_llegada',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='llego',
            field=models.BooleanField(default=False),
        ),
    ]
