# Generated by Django 3.2.7 on 2021-11-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20211109_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='llego',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
