# Generated by Django 3.2.7 on 2021-11-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_asistencia_llego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
