# Generated by Django 3.2.7 on 2021-11-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_socio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
