# Generated by Django 3.2.7 on 2021-11-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='numero_reunion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
