# Generated by Django 3.2.7 on 2021-11-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20211109_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='numero_reunion',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
