# Generated by Django 3.2.7 on 2021-11-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_asistencia_n_reunion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='llego',
            new_name='llego_a_tiempo',
        ),
    ]
